#set assignments of important variables
SE_SUN = 0
SE_MOON = 1
SE_MERCURY = 2
SE_VENUS = 3
SE_MARS = 4
SE_JUPITER = 5
SE_SATURN = 6
SE_URANUS = 7
SE_NEPTUNE = 8
SE_PLUTO = 9
SE_CHIRON = 10
SE_LILITH = 11
SE_TNODE = 12		#this must be last thing before angle stuff
SE_POF = 13
SE_VERTEX = 14
LAST_PLANET = 14

pl_name = [None] * 27
pl_name[0] = "Sun"
pl_name[1] = "Moon"
pl_name[2] = "Mercury"
pl_name[3] = "Venus"
pl_name[4] = "Mars"
pl_name[5] = "Jupiter"
pl_name[6] = "Saturn"
pl_name[7] = "Uranus"
pl_name[8] = "Neptune"
pl_name[9] = "Pluto"
pl_name[10] = "Chiron"
pl_name[11] = "Lilith"
pl_name[12] = "True Node"
pl_name[13] = "P. of Fortune"		#add a planet
pl_name[14] = "Vertex"
pl_name[LAST_PLANET + 1] = "Ascendant"
pl_name[LAST_PLANET + 2] = "Midheaven"

pl_name[LAST_PLANET + 1] = "Ascendant"
pl_name[LAST_PLANET + 2] = "House 2"
pl_name[LAST_PLANET + 3] = "House 3"
pl_name[LAST_PLANET + 4] = "House 4"
pl_name[LAST_PLANET + 5] = "House 5"
pl_name[LAST_PLANET + 6] = "House 6"
pl_name[LAST_PLANET + 7] = "House 7"
pl_name[LAST_PLANET + 8] = "House 8"
pl_name[LAST_PLANET + 9] = "House 9"
pl_name[LAST_PLANET + 10] = "MC (Midheaven)"
pl_name[LAST_PLANET + 11] = "House 11"
pl_name[LAST_PLANET + 12] = "House 12"

pl_name_var = [None] * 27

pl_name_var[0] = "sun"
pl_name_var[1] = "moon"
pl_name_var[2] = "mercury"
pl_name_var[3] = "venus"
pl_name_var[4] = "mars"
pl_name_var[5] = "jupiter"
pl_name_var[6] = "saturn"
pl_name_var[7] = "uranus"
pl_name_var[8] = "neptune"
pl_name_var[9] = "pluto"
pl_name_var[10] = "chiron"
pl_name_var[11] = "lilith"
pl_name_var[12] = "truenode"
pl_name_var[13] = "pof"		#add a planet
pl_name_var[14] = "vertex"
pl_name_var[LAST_PLANET + 1] = "ascendant"
pl_name_var[LAST_PLANET + 2] = "house2"
pl_name_var[LAST_PLANET + 3] = "house3"
pl_name_var[LAST_PLANET + 4] = "house4"
pl_name_var[LAST_PLANET + 5] = "house5"
pl_name_var[LAST_PLANET + 6] = "house6"
pl_name_var[LAST_PLANET + 7] = "house7"
pl_name_var[LAST_PLANET + 8] = "house8"
pl_name_var[LAST_PLANET + 9] = "house9"
pl_name_var[LAST_PLANET + 10] = "MC" #midheaven
pl_name_var[LAST_PLANET + 11] = "house11"
pl_name_var[LAST_PLANET + 12] = "house12"

pl_name_speed = [None] * 27

pl_name_speed[0] = "sun_speed"
pl_name_speed[1] = "moon_speed"
pl_name_speed[2] = "mercury_speed"
pl_name_speed[3] = "venus_speed"
pl_name_speed[4] = "mars_speed"
pl_name_speed[5] = "jupiter_speed"
pl_name_speed[6] = "saturn_speed"
pl_name_speed[7] = "uranus_speed"
pl_name_speed[8] = "neptune_speed"
pl_name_speed[9] = "pluto_speed"
pl_name_speed[10] = "chiron_speed"
pl_name_speed[11] = "lilith_speed"
pl_name_speed[12] = "truenode_speed"
pl_name_speed[13] = "pof_speed"		#add a planet
pl_name_speed[14] = "vertex_speed"
pl_name_speed[LAST_PLANET + 1] = "ascendant_speed"
pl_name_speed[LAST_PLANET + 2] = "house2_speed"
pl_name_speed[LAST_PLANET + 3] = "house3_speed"
pl_name_speed[LAST_PLANET + 4] = "house4_speed"
pl_name_speed[LAST_PLANET + 5] = "house5_speed"
pl_name_speed[LAST_PLANET + 6] = "house6_speed"
pl_name_speed[LAST_PLANET + 7] = "house7_speed"
pl_name_speed[LAST_PLANET + 8] = "house8_speed"
pl_name_speed[LAST_PLANET + 9] = "house9_speed"
pl_name_speed[LAST_PLANET + 10] = "MC_speed" #midheaven
pl_name_speed[LAST_PLANET + 11] = "house11_speed"
pl_name_speed[LAST_PLANET + 12] = "house12_speed"

pl_name_house = [None] * 27

pl_name_house[0] = "sun_house"
pl_name_house[1] = "moon_house"
pl_name_house[2] = "mercury_house"
pl_name_house[3] = "venus_house"
pl_name_house[4] = "mars_house"
pl_name_house[5] = "jupiter_house"
pl_name_house[6] = "saturn_house"
pl_name_house[7] = "uranus_house"
pl_name_house[8] = "neptune_house"
pl_name_house[9] = "pluto_house"
pl_name_house[10] = "chiron_house"
pl_name_house[11] = "lilith_house"
pl_name_house[12] = "truenode_house"
pl_name_house[13] = "pof_house"		#add a planet
pl_name_house[14] = "vertex_house"
pl_name_house[LAST_PLANET + 1] = "ascendant_house"
pl_name_house[LAST_PLANET + 2] = "house2_house"
pl_name_house[LAST_PLANET + 3] = "house3_house"
pl_name_house[LAST_PLANET + 4] = "house4_house"
pl_name_speed[LAST_PLANET + 5] = "house5_house"
pl_name_speed[LAST_PLANET + 6] = "house6_house"
pl_name_house[LAST_PLANET + 7] = "house7_house"
pl_name_house[LAST_PLANET + 8] = "house8_house"
pl_name_house[LAST_PLANET + 9] = "house9_house"
pl_name_house[LAST_PLANET + 10] = "MC_house" #midheaven
pl_name_house[LAST_PLANET + 11] = "house11_house"
pl_name_house[LAST_PLANET + 12] = "house12_house"

pl_ephem_number = [None] * 13

pl_ephem_number[0] = "0"
pl_ephem_number[1] = "1"
pl_ephem_number[2] = "2"
pl_ephem_number[3] = "3"
pl_ephem_number[4] = "4"
pl_ephem_number[5] = "5"
pl_ephem_number[6] = "6"
pl_ephem_number[7] = "7"
pl_ephem_number[8] = "8"
pl_ephem_number[9] = "9"
pl_ephem_number[10] = "D"
pl_ephem_number[11] = "A"
pl_ephem_number[12] = "t"

sign_name = [None] * 14

sign_name[0] = "ARIES"
sign_name[1] = "TAURUS"
sign_name[2] = "GEMINI"
sign_name[3] = "CANCER"
sign_name[4] = "LEO"
sign_name[5] = "VIRGO"
sign_name[6] = "LIBRA"
sign_name[7] = "SCORPIO"
sign_name[8] = "SAGITTARIUS"
sign_name[9] = "CAPRICORN"
sign_name[10] = "AQUARIUS"
sign_name[11] = "PISCES"
sign_name[12] = "ARIES"

name_of_sign = [None] * 14

name_of_sign[0] = "Aries"
name_of_sign[1] = "Taurus"
name_of_sign[2] = "Gemini"
name_of_sign[3] = "Cancer"
name_of_sign[4] = "Leo"
name_of_sign[5] = "Virgo"
name_of_sign[6] = "Libra"
name_of_sign[7] = "Scorpio"
name_of_sign[8] = "Sagittarius"
name_of_sign[9] = "Capricorn"
name_of_sign[10] = "Aquarius"
name_of_sign[11] = "Pisces"
name_of_sign[12] = "Aries"
